{
  "language": "node_js",
  "sudo": "required",
  "node_js": "6.11.3",
  "install": [
    "npm install"
  ],
  "before_scripts": [
    
  ],
  "script": [
    #Display Firefox
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",

    #Run Unit Tests
    "npm test",

    #Update webdriver-manager
    "npm run update-e2e",

    #Start site
    "node server.js &",

    #Start webdriver-manager & run e2e tests
    "npm run e2e",

    #Kill site
    "killall node"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}