{
  "language": "node_js",
  "sudo": "required",
  "node_js": "6.11.3",
  "install": [
    "npm install"
  ],
  "before_scripts": [
    
  ],
  "script": [
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "npm test"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}