language": node_js
sudo": required
node_js: 6.11.3
install: npm install
jobs:
  include:
    - stage: Unit Tests
      script: 
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

        #Unit Tests
        - npm test

    - stage: e2e Tests
      script:
        #Update webdriver-manager
        - npm run update-e2e

        #Start site
        - node server.js &

        #Start webdriver-manager & run e2e tests
        #- npm run e2e

        #Shutdown webdriver-manager
        #- npm run shutdown-e2e
        #Kill site
        - killall node
        
group: stable
dist: trusty
os: linux