{
  "language": "node_js",
  "sudo": "required",
  "node_js": "6.11.3",
  "install": [
    "npm install"
  ],
  "before_scripts":[
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start"
  ]
  "script": [
    "npm test",
    "npm run update-e2e",
    "node server.js &",
    "npm run e2e",
    "killall node"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}